import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.sass";

import Script from "next/script";
import React from "react";
import { MetaData } from "../components/MetaData";
import { Preview } from "../components/Preview";
import {
  validateDescription,
  validateTitle,
  validateUrl,
} from "../utils/validators";
import { readElementAsync } from "../utils/readElementAsync";

declare const CustomElement: any;

type Elements = {
  readonly title: string;
  readonly description: string;
  readonly url: string;
};

const noData: Elements = {
  title: "no-title",
  description: "no-description",
  url: "no-url",
};

enum InitializationState {
  Initializing = "initializing",
  Failed = "failed",
  Loaded = "loaded",
}

const Home: NextPage = () => {
  const [initializationState, setInitializationState] = React.useState(InitializationState.Initializing);
  const [elements, setElements] = React.useState<Elements>(noData);

  React.useEffect(() => {
    if (!(initializationState === InitializationState.Loaded)) return;

    const initialize = async () => {
      try {
        const promises = ["title", "meta_description", "friendly_url"].map(
          readElementAsync
        );
        const [title, description, url] = await Promise.all(promises);
        setElements({
          title,
          description,
          url,
        });

        CustomElement.setHeight(600);
      } catch (error) {
        console.error(
          `Something went wrong while initializing custom element: ${error}`
        );
        setInitializationState(InitializationState.Failed);
      }
    };

    initialize();
  }, [initializationState, setInitializationState]);

  if (initializationState === InitializationState.Failed) {
    return <div>Failed</div>;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script
        onLoad={() => setInitializationState(InitializationState.Loaded)}
        src="https://app.kontent.ai/js-api/custom-element/v1/custom-element.min.js"
      />

      <main className={styles.main}>
        <Preview {...elements} />
        <div className={styles.container}>
          <MetaData
            title="Meta title:"
            value={elements.title}
            errors={Array.from(validateTitle(elements.title))}
          />
          <MetaData
            title="Meta description:"
            value={elements.description}
            errors={Array.from(validateDescription(elements.description))}
          />
          <MetaData
            title="Friendly url:"
            value={elements.url}
            errors={Array.from(validateUrl(elements.url))}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
